server:
  port: 5000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://nacos:8848
  application:
    name: alarm-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    tomcat:
      max-active: 20
    url: jdbc:mysql://mysql:3306/issues?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
    username: root
  jpa:
    database: mysql
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true

