name: demo5
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  rxdart:
  font_awesome_flutter:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  shared_preferences: ^0.5.12+2
  flutter_settings_screens: ^0.2.1
  validators: ^2.0.0
  provider: ^4.3.2+2
  permission_handler: ^5.0.1+1
  smart_select: ^4.3.2
  cupertino_icons: ^1.0.0
  english_words: ^3.1.0
  flutter_circular_slider : ^2.5.0
  day_night_time_picker: ^0.3.0
  flutter_animation_progress_bar: ^1.0.5
  flutter_gradient_colors: ^1.0.0
  flutter_slidable: ^0.5.7
  easy_dialog: ^1.0.5
  grouped_buttons: ^1.0.4
  day_picker: ^1.0.1
  toggle_switch: ^0.1.8
  flutter_swiper: ^1.1.6
  circular_profile_avatar: ^1.0.6
  slide_countdown_clock: ^1.0.3
  audioplayers: ^0.13.1
  flutter_screenutil: ^1.0.2
  image_picker: ^0.6.7+12
  path_provider: ^1.6.22
  quiz_view: ^1.0.3
  argon_buttons_flutter: ^1.0.6
  flutter_spinkit: ^4.1.2+1
  sqflite: ^1.3.1

dev_dependencies:
  build_runner: ^1.9.0
  flutter_test:
    sdk: flutter
  json_serializable: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec




# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Miriam
      fonts:
        - asset: assets/fonts/MiriamLibre-Regular.ttf
          weight: 400
        - asset: assets/fonts/MiriamLibre-Bold.ttf
    - family: Nycd
      fonts:
        - asset: assets/fonts/NothingYouCouldDo-Regular.ttf
    - family: ZhiMangXing
      fonts:
        - asset: assets/fonts/ZhiMangXing-Regular.ttf
    - family: KeShi
      fonts:
        - asset: assets/fonts/KeShi.ttf
    - family: Knewave
      fonts:
        - asset: assets/fonts/Knewave-Regular.ttf
  assets:
    - assets/image/frog.png
    - assets/image/frog2.png
    - assets/image/frog3.png
    - assets/image/cat.jpg
    - assets/image/logo.png
    - assets/image/Froglogo.png
    - assets/image/math.png
    - assets/image/music.png
    - assets/image/game.png
    - assets/image/camera.png
    - assets/image/random.png
    - assets/image/arithmetic.png
    - assets/image/shake.png
    - assets/image/tree1.png
    - assets/image/tree2.png
    - assets/image/tree3.png
    - assets/image/tree4.png
    - assets/image/animal1.png
    - assets/image/animal2.png
    - assets/image/animal3.png
    - assets/image/animal4.png
    - assets/image/animal5.png
    - assets/image/animal6.png
    - assets/image/animal7.png
    - assets/image/animal8.png
    - assets/image/bigTree.png
    - assets/image/frogChiLeft.png
    - assets/image/frogMa.png
    - assets/image/frogChiRight.png
    - assets/image/animalsLeft.png
    - assets/image/animalsRight.png
    - assets/image/takePhotoLeft.png
    - assets/image/takePhotoRight.png
    - assets/image/photoBorder.png
    - assets/image/frogPlay1.png
    - assets/image/frogPlay2.png
    - assets/image/frogPlay3.png
    - assets/image/frogPlay4.png
    - assets/image/frogStudy1.png
    - assets/image/frogStudy2.png
    - assets/image/frogStudy3.png
    - assets/image/frogStudy4.png
    - assets/image/frogGraduate.png
    - assets/image/banner.png
    - assets/audios/audio1.mp3
    - assets/audios/audio2.mp3
    - assets/audios/audio3.mp3
    - assets/audios/audio4.mp3
    - assets/audios/audio5.mp3
    - jsons/profile.json
    - jsons/settings.json
    - jsons/user.json
    - jsons/frog.json
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
